### ISSUE TITLE
scroll bar  have Tween animation ??

### ISSUE THREAD

**Issue by zhuxiujia** [PistonDevelopers/conrod#1353] opened 2020-06-05 17:52 UTC
scroll bar  have Tween animation ??
It looks too stiff
we need an Transition animation。
and I think many GUI controls can be built in, such as flutter

**Comment by alvinhochun** [comment] 2020-08-25 10:49
I would file this as a duplicate of #1202.

**Closed by alvinhochun** 2020-08-25 10:49 UTC
