### ISSUE TITLE
screen dislocation (OSX)

### ISSUE THREAD

**Issue by Jeff-Castles** [PistonDevelopers/conrod#1134] opened 2018-02-12 14:26 UTC
My Mac version: 10.13.3

When I execute `  cargo run --release --features "winit glium" --example all_winit_glium`, it was successfully compiled.

However ,as shown in Fig. below, it is not as expected.

![1518444409370](https://user-images.githubusercontent.com/33049497/36100578-ad394eee-1041-11e8-8b3e-89f7074ea98f.jpg)

**Comment by mitchmindtree** [comment] 2018-02-12 14:45
If you resize the window after it has initialised does it fix the issue? I've also noticed this problem appear on mac recently.

Either way, this issue likely comes from a problem in an upstream crate (perhaps `glium`?), or perhaps it has been fixed upstream and we haven't yet updated to the fixed version. I don't currently have access to a macos machine but perhaps you could try running the [glium](https://github.com/glium/glium) examples to test this?

**Comment by syssecfsu** [comment] 2018-02-12 15:16
I have the same problem with Conrod on the Mac OS X. 

I just quickly tested the examples in glium. It seems that the problem is indeed caused by glium. 
The following is the screenshot of tutorial 7. The teapot is supposed to be centered in a correct rendition. 

<img width="431" alt="screen shot 2018-02-12 at 10 12 19 am" src="https://user-images.githubusercontent.com/17749704/36103557-a98d9ade-0fdd-11e8-9823-c6f501b4ee32.png">

**Comment by harvath** [comment] 2018-02-25 18:07
Apparently this is a problem with the [winit](https://github.com/tomaka/winit) library. 
([glium](https://github.com/glium/glium) depends on [glutin](https://github.com/tomaka/glutin), which depends on [winit](https://github.com/tomaka/winit))

I built conrod with winit from [this PR](https://github.com/tomaka/winit/pull/359), and it worked perfectly. Not sure when this PR will be merged, but this is a serious bug that makes the library virtually unusable for OSX users so I had to share this

**Comment by mitchmindtree** [comment] 2018-02-25 23:40
Thanks @harvath, if you could comment in tomaka/winit#359 letting tomaka know that you've tested the PR on macos and that it fixes a few issues it will likely allow him to go ahead with merging it. The biggest blocker for mac PRs on winit is that tomaka doesn't have a mac to test on so he normally has to rely on another mac user testing and approving the PR before he can merge :+1: I no longer have access to a mac otherwise I'd do this myself!

**Comment by quatrezoneilles** [comment] 2018-04-09 09:58
That problem is now fixed in winit 0.12 but there's an incompatible change somewhere in event conversion.

```rust
error[E0308]: mismatched types
  --> examples/text.rs:73:76
   |
73 |                 if let Some(event) = conrod::backend::winit::convert_event(event.clone(), &display) {
   |                                                                            ^^^^^^^^^^^^^ expected enum `winit::events::Event`, found enum `conrod::<unnamed>::<unnamed>::Event`
   |
   = note: expected type `winit::events::Event`
              found type `conrod::<unnamed>::<unnamed>::Event`
note: Perhaps two different versions of crate `winit` are being used?
```

**Comment by mitchmindtree** [comment] 2018-04-09 10:09
@quatrezoneilles this is due to the requirement of our `winit` dependency to have the same version as `glutin`'s `winit` dependency and `glium`'s `winit` dependency (I have a PR for updating glutin [here](https://github.com/tomaka/glutin/pull/1010)) - if these are different, rustc will presume they are different types or traits altogether.

While we wait for glutin and glium to update, I have a [branch here](https://github.com/mitchmindtree/conrod/tree/winit_glium_update) that should work fine (just remember to `cargo update` before running it).

I'll leave this open until the fix actually makes it to master and gets published.

**Comment by quatrezoneilles** [comment] 2018-04-09 10:58
Yes, it works now!  Thanks!  All the examples work (except for file_navigator.)

**Closed** 2018-04-17 08:36 UTC
