### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Flaflo** [PistonDevelopers/conrod#838] opened 2016-10-07 14:17 UTC
After downloading some packages i get spit out this:
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name

and after downloading another packages it throws this along with message that there where some issues while building:

LLVM ERROR: IO failure on output stream.
error: failed to run custom build command for `miniz-sys v0.1.7`
process didn't exit successfully: `C:\***\conrod\target\debug\build\miniz-sys-60c8d67696f63a43\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-pc-windows-gnu")
debug=true opt-level=0
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-o" "C:\\***\\conrod\\target\\debug\\build\\miniz-sys-60c8d67696f63a43\\out\\miniz.o" "-c" "miniz.c"

failed to execute command: Das System kann die angegebene Datei nicht finden. (os error 2)
Is `gcc.exe` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)

--- stderr
thread 'main' panicked at 'explicit panic', C:\***\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.35\src\lib.rs:897
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by mitchmindtree** [comment] 2016-10-08 03:12
Thanks for the issue - looks like this might be a duplicate of #811 which seems to be a duplicate of alexcrichton/flate2-rs#33. Perhaps [this comment](https://github.com/alexcrichton/flate2-rs/issues/33#issuecomment-170772849) might solve it?

Going to close this issue for now, but feel free to re-open it if you are still running into issues.

**Closed by mitchmindtree** 2016-10-08 03:12 UTC
