### ISSUE TITLE
'windows' in canvas example reluctant to be dragged

### ISSUE THREAD

**Issue by Kingsquee** [PistonDevelopers/conrod#879] opened 2016-11-23 08:17 UTC
Steps to reproduce:
1) ```cargo run --release --example canvas```
2) hold down on the title of either the 'Blue' or 'Orange' "window"
3) drag the window around rapidly - circles works well
4) watch it occasionally 'fall off' your cursor.
if you keep your mouse held down, you can move your cursor over the window title again to 'pick it up' again. 

Fedora 24, Xorg, GNOME Shell 3.20.4

**Comment by mitchmindtree** [comment] 2016-11-23 08:59
Going to close this as I believe it is a dupe of #788.

**Closed by mitchmindtree** 2016-11-23 08:59 UTC
