### ISSUE TITLE
CPU activity

### ISSUE THREAD

**Issue by joeblew99** [PistonDevelopers/conrod#441] opened 2015-05-18 13:42 UTC
I am on OSX Yosemite

When i run the examples they are using over 50% of the CPU when idling.
Have i got something wrong or is this the current state of the architecture ?

**Comment by mitchmindtree** [comment] 2015-05-18 13:50
Yes we're a bit slow atm as we've been adding a lot of features lately without doing much optimising - there's certainly a lot of potential for improvement.

I'll start up a separate issue listing areas I have in mind for improvement.

Also, rust code normally improves multiple times over when optimising with the `--release` flag - I'm also on yosemite and also get about 50% cpu in debug, however in release I go down to 20-25%. We can still do a lot better :)

Thanks for the issue!

**Comment by mitchmindtree** [comment] 2015-05-18 14:07
@joeblew99 I made a start on a list [here](https://github.com/PistonDevelopers/conrod/issues/442) - if you find anything else feel free to add to it!

**Comment by viperscape** [comment] 2015-05-18 15:01
What might be the cause of high cpu, @mitchmindtree. Is there much polling during each render cycle?

**Comment by cybergeek94** [comment] 2015-08-13 22:13
The `all_widget` examples sets UPS and max FPS but the others don't AFAICT, I wonder how many cycles we could save just by setting a maximum framerate.

**Comment by mitchmindtree** [comment] 2016-02-22 15:24
Going to close this in favour of tracking #664 for now.

**Closed by mitchmindtree** 2016-02-22 15:24 UTC
